# delta_x: 0.0 # The x offset between the origin of the simulator coordinate frame and the map coordinate frame published by fake_localization.
# delta_y: 0.0 # The y offset between the origin of the simulator coordinate frame and the map coordinate frame published by fake_localization.
# delta_yaw: 0.0 # The yaw offset between the origin of the simulator coordinate frame and the map coordinate frame published by fake_localization.
# odom_frame_id: "odom" # The name of the odometric frame of the robot.
# base_frame_id: base_link # The base frame of the robot. New in 1.1.3
# global_frame_id: /map # The frame in which to publish the global_frame_id→odom_frame_id transform over tf. New in 1.1.3
