robot_actuators:
    pose:
      comm: TOPIC
      node: initialpose
      type: geometry_msgs/PoseWithCovarianceStamped
    talk:
      comm: ACTION
      node: gtts_ros/goal
      type: gtts_ros/TalkActionGoal
    hear:
      comm: SERVICE
      node: Recognition
      type: gsr_ros/Start
    move:
      comm: TOPIC
      node: cmd_vel
      type: geometry_msgs/Twist
    goto:
      comm: ACTION
      node: move_base/goal
      type: move_base_msgs/MoveBaseActionGoal
    gotosocial:
      comm: ACTION
      node: social_navigation/goal
      type: social_move_base/SocialMoveBaseActionGoal
    follow:
      comm: ACTION
      node: social_navigation/goto/goal
      type: social_navigation/GotoActionGoal
    savelocal:
      comm: SERVICE
      node: /map/save_local
      type: map/SaveLocal
    head:
      comm: SERVICE
      node: head_interface
      type: hera_control/Head_service
